truncate table Brand
truncate table Category
truncate table Colour
truncate table Customer
truncate table Employee
truncate table Gift_Voucher
truncate table Product
truncate table Product_Dispatch
truncate table Product_Dispatch_Item
truncate table Product_Images
truncate table Product_MRP
truncate table Product_SKU_Mapping
truncate table Size
truncate table Size_Group
truncate table Sub_Category
truncate table Tax
truncate table Vendor
truncate table Vendor_Article_Mapping
truncate table Vendor_Bank_Details
truncate table Vendor_Article_Mapping
truncate table Vendor_Brand_Mapping
truncate table Vendor_Category_Mapping
truncate table Vendor_SubCategory_Mapping
truncate table VendorContact